# Generated by Django 4.2.9 on 2024-03-07 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manutencao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=40, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=40, verbose_name='Sobrenome')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Aquario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Aquario')),
                ('volume', models.IntegerField(verbose_name='Volume')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_montagem', models.DateField(verbose_name='Data da Montagem')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=manutencao.models.PathAndRename('aquarios/'))),
            ],
            options={
                'verbose_name': 'Aquario',
                'verbose_name_plural': 'Aquarios',
            },
        ),
        migrations.CreateModel(
            name='Especime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=100, verbose_name='Nome popular')),
                ('nome_cientifico', models.CharField(max_length=100, unique=True, verbose_name='Nome científico')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=manutencao.models.PathAndRename('especimes/'))),
            ],
            options={
                'verbose_name': 'Espécime',
                'verbose_name_plural': 'Espécimes',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Aquario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aquario', models.CharField(max_length=20, unique=True, verbose_name='Tipo do aquario')),
            ],
            options={
                'verbose_name': 'Tipo de Aquario',
                'verbose_name_plural': 'Tipos de Aquários',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Especime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_especime', models.CharField(max_length=100, unique=True, verbose_name='Espécime')),
            ],
            options={
                'verbose_name': 'Tipo de espécime',
                'verbose_name_plural': 'Tipos de Espécimes',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manutencao', models.CharField(max_length=50, unique=True, verbose_name='Tipo da manutenção')),
            ],
            options={
                'verbose_name': 'Tipo de Manutenção',
                'verbose_name_plural': 'Tipos de Manutenção',
            },
        ),
        migrations.CreateModel(
            name='Populacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('aquario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populacao', to='manutencao.aquario')),
                ('especime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.especime')),
            ],
            options={
                'verbose_name': 'População',
                'verbose_name_plural': 'Populações',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da manutenção')),
                ('ph', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Ph')),
                ('temperatura', models.IntegerField(blank=True, null=True, verbose_name='Temperatura')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('aquario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='manutencao.aquario')),
                ('tipo_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.tipo_manutencao')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
        ),
        migrations.AddField(
            model_name='especime',
            name='tipo_especime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.tipo_especime'),
        ),
        migrations.AddField(
            model_name='aquario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.tipo_aquario'),
        ),
        migrations.AddField(
            model_name='aquario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
