# Generated by Django 4.2.9 on 2024-03-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_alter_especime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='populacao',
            options={'ordering': ['especime'], 'verbose_name': 'População', 'verbose_name_plural': 'Populações'},
        ),
    ]
