# Generated by Django 4.2.9 on 2024-03-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='tipo_aquario',
            options={'ordering': ['tipo_aquario'], 'verbose_name': 'Tipo de Aquario', 'verbose_name_plural': 'Tipos de Aquários'},
        ),
        migrations.AlterModelOptions(
            name='tipo_especime',
            options={'ordering': ['tipo_especime'], 'verbose_name': 'Tipo de espécime', 'verbose_name_plural': 'Tipos de Espécimes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_manutencao',
            options={'ordering': ['tipo_manutencao'], 'verbose_name': 'Tipo de Manutenção', 'verbose_name_plural': 'Tipos de Manutenção'},
        ),
    ]
