# Generated by Django 4.2.9 on 2024-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0008_alter_manutencao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['ordenacao']},
        ),
        migrations.AddField(
            model_name='aviso',
            name='ordenacao',
            field=models.IntegerField(default=1, verbose_name='Ordenação'),
            preserve_default=False,
        ),
    ]
