# Generated by Django 4.2.9 on 2024-03-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0009_alter_aviso_options_aviso_ordenacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencao',
            options={'ordering': ['-data'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
    ]
