# Generated by Django 4.2.9 on 2024-03-13 19:14

import django.core.validators
from django.db import migrations, models
import manutencao.models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0011_alter_especime_nome_cientifico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=manutencao.models.PathAndRename('aquarios/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='especime',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=manutencao.models.PathAndRename('especimes/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
