# Generated by Django 4.2.9 on 2024-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0012_alter_aquario_foto_alter_especime_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especime',
            name='nome_cientifico',
            field=models.CharField(default='Editar', max_length=100, verbose_name='Nome científico'),
        ),
    ]
