# Generated by Django 4.2.9 on 2024-03-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0013_alter_especime_nome_cientifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especime',
            name='nome_cientifico',
            field=models.CharField(default='Nome Científico', max_length=100, verbose_name='Nome científico'),
        ),
    ]
